version: '3.8'

services:
  web:
    build: .
    ports:
      - "8086:8086"
    environment:
      - APP_NAME=Skup API
      - FORCE_SSL=false
      - SKIP_AUTH=true
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.docker # legg til DATABASE_URL i denne filen