version: '3.8'

services:
  web:
    build: .
    ports:
      - "8086:8086"
    environment:
      - DATABASE_URL=postgresql://eilifjohansen@host.docker.internal:5432/skupapi
      - FORCE_SSL=false
      - SKIP_AUTH=true
      - PYTHONUNBUFFERED=1