apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: team-researchops
  name: skup-backend
  namespace: team-researchops
spec:
  env:
    - name: "DATABASE_URL"
      value: "$(NAIS_DATABASE_SKUP_BACKEND_SKUP_BACKEND_URL)"
    - name: "FORCE_SSL"
      value: "true"
    - name: "SSL_ROOT_CERT"
      value: "/var/run/secrets/nais.io/sqlcertificate/root-cert.pem"
    - name: "SSL_CERT"
      value: "/var/run/secrets/nais.io/sqlcertificate/cert.pem"
    - name: "SSL_KEY"
      value: "/var/run/secrets/nais.io/sqlcertificate/key.pem"
  image: "{{ image }}"
  port: 8086
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: skup-backend
            users:
              - name: datastream
        diskAutoresize: true
  accessPolicy:
    inbound:
      rules:
        - application: skup
  ingresses:
    - https://skupapi.intern.nav.no
  liveness:
    path: /api/isalive
    initialDelay: 20
    periodSeconds: 6
    timeout: 2
  readiness:
    path: /api/isready
    initialDelay: 20
    periodSeconds: 6
    timeout: 10
